### ISSUE TITLE
想请教一下关于IR的问题

### ISSUE THREAD

**Issue by clyran** [nzh63/syc#4]
请问一下您采用的IR是何种类型？感觉更偏向汇编一点，后面的优化思路又是怎样的呢？
还有就是语义分析是在哪里做的？
我正在学习编译原理并尝试实现sysY的编译器，如蒙指教，不胜感激！

**Comment by tszdanger** [comment]
All the details are shown in the official website, and we are very sorry to tell you that we cannot remember all the details. Fortunately, if you are studying in HITSZ, our lab had kept the slides we made last year and you may can ask the teaching team in HITSZ. But since all the dev members are now working and don't have enough time to write down the detail instruction, we are so sorry for that.
Also, we develop a online demo to keep it clear for teaching.
Enjoying the compiler. You can update anything you want and we will try to keep it updated.

**Comment by clyran** [comment]
Thank you for your reply, maybe someday I would study in HITSZ.

**Comment by rid-sun** [comment]
> 请问一下您采用的IR是何种类型？感觉更偏向汇编一点，后面的优化思路又是怎样的呢？ 还有就是语义分析是在哪里做的？ 我正在学习编译原理并尝试实现sysY的编译器，如蒙指教，不胜感激！

似乎并没有语义分析。在20年的竞赛中也未有此样例。

**Comment by rid-sun** [comment]
> 请问一下您采用的IR是何种类型？感觉更偏向汇编一点，后面的优化思路又是怎样的呢？ 还有就是语义分析是在哪里做的？ 我正在学习编译原理并尝试实现sysY的编译器，如蒙指教，不胜感激！

There seems to be no semantic processing in this project (In fact, there is no such testing in the 2020 test case. And the following code is teatable).
`void foo(int a){
     return 0;
}
foo("bar");`
