### ISSUE TITLE
A small bug and a question

### ISSUE THREAD

**Issue by clyran** [nzh63/syc#6]
I find that const value can be changed in your program!!!
```c++
const int a=6;
int main()
{
    a=4;
}
```
it can be compile successfully.
by the way,I want to ask a question, what's the meaning of PHI_MOV ,PHI_block and the fake(do)  while generating the irs of whilestatement.
Basically,I even not understand clearly the use of PHI_MOV,dose it have something to do with phi node or SSA?
I would be grateful for you answer.

**Comment by nzh63** [comment]
We didn't do any validation on the input. You need to make sure your input conforms to the SysY specification -- otherwise we don't know what's going to happen.

SSA form requires that every variable is assigned only exactly once. The PHI_MOV instruction is used to  chooses the right value of variable, depending on the control flow. The PHI_MOV directive always comes in pairs. Consider the following instructions:
```
LABEL    BASE_BLOCK_1
// ...
PHI_MOV  %3, %1
JMP      BASE_BLOCK_3

LABEL    BASE_BLOCK_2
// ...
PHI_MOV  %3, %2
JMP      BASE_BLOCK_3

LABEL    BASE_BLOCK_3
// ...
```
They are similar to the following LLVM IR:
```
BASE_BLOCK_1:
  // ...
  br label %BASE_BLOCK_3
BASE_BLOCK_2:
  // ...
  br label %BASE_BLOCK_3
BASE_BLOCK_3:
  %3= phi i32 [%1, %BASE_BLOCK_1], [%2, %BASE_BLOCK_2]
```

I remember that we don't have anything called PHI_block. Did you make a mistake?

The code that generates IR of while statement is A LUMP OF SHIT. I can't understand the clear meaning of this code now. The general purpose is to generate the correct PHI statement when encountering break statement  and continue statement.
